sentences = [
	"grasp the block",
	"grasp the block",
	"grasp the block",
	"grasp the ball",
	"grasp the ball",
	"grasp the ball",
	"grasp the plate",
	"grasp the plate",
	"grasp the plate",
	"grasp the cup",
	"grasp the cup",
	"grasp the cup",
	"grasp the disc",
	"grasp the disc",
	"grasp the disc",
	"grasp the book",
	"grasp the book",
	"grasp the book",
	"grasp the blackboard",
	"grasp the blackboard",
	"grasp the blackboard",
	"grasp the bottle",
	"grasp the bottle",
	"grasp the bottle",
	"grasp the grape",
	"grasp the grape",
	"grasp the grape",
	"grasp the apple",
	"grasp the apple",
	"grasp the apple",
	"grasp the banana",
	"grasp the banana",
	"grasp the banana",
	"grasp the bowl",
	"grasp the bowl",
	"grasp the bowl",
	"grasp the knife",
	"grasp the knife",
	"grasp the knife",
	"grasp the pencil",
	"grasp the pencil",
	"grasp the pencil",
	"grasp the paper sheet",
	"grasp the paper sheet",
	"grasp the paper sheet"
	]
