sentences = [
	"hold the block",
	"hold the block",
	"hold the block",
	"hold the ball",
	"hold the ball",
	"hold the ball",
	"hold the plate",
	"hold the plate",
	"hold the plate",
	"hold the cup",
	"hold the cup",
	"hold the cup",
	"hold the disc",
	"hold the disc",
	"hold the disc",
	"hold the book",
	"hold the book",
	"hold the book",
	"hold the blackboard",
	"hold the blackboard",
	"hold the blackboard",
	"hold the bottle",
	"hold the bottle",
	"hold the bottle",
	"hold the grape",
	"hold the grape",
	"hold the grape",
	"hold the apple",
	"hold the apple",
	"hold the apple",
	"hold the banana",
	"hold the banana",
	"hold the banana",
	"hold the bowl",
	"hold the bowl",
	"hold the bowl",
	"hold the knife",
	"hold the knife",
	"hold the knife",
	"hold the pencil",
	"hold the pencil",
	"hold the pencil",
	"hold the paper sheet",
	"hold the paper sheet",
	"hold the paper sheet"
	]
