sentences = [
	"put the block touching the ball",
	"put the block touching the ball",
	"put the block touching the ball",
	"put the block touching the plate",
	"put the block touching the plate",
	"put the block touching the plate",
	"put the block touching the cup",
	"put the block touching the cup",
	"put the block touching the cup",
	"put the block touching the disc",
	"put the block touching the disc",
	"put the block touching the disc",
	"put the block touching the book",
	"put the block touching the book",
	"put the block touching the book",
	"put the block touching the blackboard",
	"put the block touching the blackboard",
	"put the block touching the blackboard",
	"put the block touching the bottle",
	"put the block touching the bottle",
	"put the block touching the bottle",
	"put the block touching the grape",
	"put the block touching the grape",
	"put the block touching the grape",
	"put the block touching the apple",
	"put the block touching the apple",
	"put the block touching the apple",
	"put the block touching the banana",
	"put the block touching the banana",
	"put the block touching the banana",
	"put the block touching the bowl",
	"put the block touching the bowl",
	"put the block touching the bowl",
	"put the block touching the knife",
	"put the block touching the knife",
	"put the block touching the knife",
	"put the block touching the pencil",
	"put the block touching the pencil",
	"put the block touching the pencil",
	"put the block touching the paper sheet",
	"put the block touching the paper sheet",
	"put the block touching the paper sheet",
	"put the ball touching the block",
	"put the ball touching the block",
	"put the ball touching the block",
	"put the ball touching the plate",
	"put the ball touching the plate",
	"put the ball touching the plate",
	"put the ball touching the cup",
	"put the ball touching the cup",
	"put the ball touching the cup",
	"put the ball touching the disc",
	"put the ball touching the disc",
	"put the ball touching the disc",
	"put the ball touching the book",
	"put the ball touching the book",
	"put the ball touching the book",
	"put the ball touching the blackboard",
	"put the ball touching the blackboard",
	"put the ball touching the blackboard",
	"put the ball touching the bottle",
	"put the ball touching the bottle",
	"put the ball touching the bottle",
	"put the ball touching the grape",
	"put the ball touching the grape",
	"put the ball touching the grape",
	"put the ball touching the apple",
	"put the ball touching the apple",
	"put the ball touching the apple",
	"put the ball touching the banana",
	"put the ball touching the banana",
	"put the ball touching the banana",
	"put the ball touching the bowl",
	"put the ball touching the bowl",
	"put the ball touching the bowl",
	"put the ball touching the knife",
	"put the ball touching the knife",
	"put the ball touching the knife",
	"put the ball touching the pencil",
	"put the ball touching the pencil",
	"put the ball touching the pencil",
	"put the ball touching the paper sheet",
	"put the ball touching the paper sheet",
	"put the ball touching the paper sheet",
	"put the plate touching the block",
	"put the plate touching the block",
	"put the plate touching the block",
	"put the plate touching the ball",
	"put the plate touching the ball",
	"put the plate touching the ball",
	"put the plate touching the cup",
	"put the plate touching the cup",
	"put the plate touching the cup",
	"put the plate touching the disc",
	"put the plate touching the disc",
	"put the plate touching the disc",
	"put the plate touching the book",
	"put the plate touching the book",
	"put the plate touching the book",
	"put the plate touching the blackboard",
	"put the plate touching the blackboard",
	"put the plate touching the blackboard",
	"put the plate touching the bottle",
	"put the plate touching the bottle",
	"put the plate touching the bottle",
	"put the plate touching the grape",
	"put the plate touching the grape",
	"put the plate touching the grape",
	"put the plate touching the apple",
	"put the plate touching the apple",
	"put the plate touching the apple",
	"put the plate touching the banana",
	"put the plate touching the banana",
	"put the plate touching the banana",
	"put the plate touching the bowl",
	"put the plate touching the bowl",
	"put the plate touching the bowl",
	"put the plate touching the knife",
	"put the plate touching the knife",
	"put the plate touching the knife",
	"put the plate touching the pencil",
	"put the plate touching the pencil",
	"put the plate touching the pencil",
	"put the plate touching the paper sheet",
	"put the plate touching the paper sheet",
	"put the plate touching the paper sheet",
	"put the cup touching the block",
	"put the cup touching the block",
	"put the cup touching the block",
	"put the cup touching the ball",
	"put the cup touching the ball",
	"put the cup touching the ball",
	"put the cup touching the plate",
	"put the cup touching the plate",
	"put the cup touching the plate",
	"put the cup touching the disc",
	"put the cup touching the disc",
	"put the cup touching the disc",
	"put the cup touching the book",
	"put the cup touching the book",
	"put the cup touching the book",
	"put the cup touching the blackboard",
	"put the cup touching the blackboard",
	"put the cup touching the blackboard",
	"put the cup touching the bottle",
	"put the cup touching the bottle",
	"put the cup touching the bottle",
	"put the cup touching the grape",
	"put the cup touching the grape",
	"put the cup touching the grape",
	"put the cup touching the apple",
	"put the cup touching the apple",
	"put the cup touching the apple",
	"put the cup touching the banana",
	"put the cup touching the banana",
	"put the cup touching the banana",
	"put the cup touching the bowl",
	"put the cup touching the bowl",
	"put the cup touching the bowl",
	"put the cup touching the knife",
	"put the cup touching the knife",
	"put the cup touching the knife",
	"put the cup touching the pencil",
	"put the cup touching the pencil",
	"put the cup touching the pencil",
	"put the cup touching the paper sheet",
	"put the cup touching the paper sheet",
	"put the cup touching the paper sheet",
	"put the disc touching the block",
	"put the disc touching the block",
	"put the disc touching the block",
	"put the disc touching the ball",
	"put the disc touching the ball",
	"put the disc touching the ball",
	"put the disc touching the plate",
	"put the disc touching the plate",
	"put the disc touching the plate",
	"put the disc touching the cup",
	"put the disc touching the cup",
	"put the disc touching the cup",
	"put the disc touching the book",
	"put the disc touching the book",
	"put the disc touching the book",
	"put the disc touching the blackboard",
	"put the disc touching the blackboard",
	"put the disc touching the blackboard",
	"put the disc touching the bottle",
	"put the disc touching the bottle",
	"put the disc touching the bottle",
	"put the disc touching the grape",
	"put the disc touching the grape",
	"put the disc touching the grape",
	"put the disc touching the apple",
	"put the disc touching the apple",
	"put the disc touching the apple",
	"put the disc touching the banana",
	"put the disc touching the banana",
	"put the disc touching the banana",
	"put the disc touching the bowl",
	"put the disc touching the bowl",
	"put the disc touching the bowl",
	"put the disc touching the knife",
	"put the disc touching the knife",
	"put the disc touching the knife",
	"put the disc touching the pencil",
	"put the disc touching the pencil",
	"put the disc touching the pencil",
	"put the disc touching the paper sheet",
	"put the disc touching the paper sheet",
	"put the disc touching the paper sheet",
	"put the book touching the block",
	"put the book touching the block",
	"put the book touching the block",
	"put the book touching the ball",
	"put the book touching the ball",
	"put the book touching the ball",
	"put the book touching the plate",
	"put the book touching the plate",
	"put the book touching the plate",
	"put the book touching the cup",
	"put the book touching the cup",
	"put the book touching the cup",
	"put the book touching the disc",
	"put the book touching the disc",
	"put the book touching the disc",
	"put the book touching the blackboard",
	"put the book touching the blackboard",
	"put the book touching the blackboard",
	"put the book touching the bottle",
	"put the book touching the bottle",
	"put the book touching the bottle",
	"put the book touching the grape",
	"put the book touching the grape",
	"put the book touching the grape",
	"put the book touching the apple",
	"put the book touching the apple",
	"put the book touching the apple",
	"put the book touching the banana",
	"put the book touching the banana",
	"put the book touching the banana",
	"put the book touching the bowl",
	"put the book touching the bowl",
	"put the book touching the bowl",
	"put the book touching the knife",
	"put the book touching the knife",
	"put the book touching the knife",
	"put the book touching the pencil",
	"put the book touching the pencil",
	"put the book touching the pencil",
	"put the book touching the paper sheet",
	"put the book touching the paper sheet",
	"put the book touching the paper sheet",
	"put the blackboard touching the block",
	"put the blackboard touching the block",
	"put the blackboard touching the block",
	"put the blackboard touching the ball",
	"put the blackboard touching the ball",
	"put the blackboard touching the ball",
	"put the blackboard touching the plate",
	"put the blackboard touching the plate",
	"put the blackboard touching the plate",
	"put the blackboard touching the cup",
	"put the blackboard touching the cup",
	"put the blackboard touching the cup",
	"put the blackboard touching the disc",
	"put the blackboard touching the disc",
	"put the blackboard touching the disc",
	"put the blackboard touching the book",
	"put the blackboard touching the book",
	"put the blackboard touching the book",
	"put the blackboard touching the bottle",
	"put the blackboard touching the bottle",
	"put the blackboard touching the bottle",
	"put the blackboard touching the grape",
	"put the blackboard touching the grape",
	"put the blackboard touching the grape",
	"put the blackboard touching the apple",
	"put the blackboard touching the apple",
	"put the blackboard touching the apple",
	"put the blackboard touching the banana",
	"put the blackboard touching the banana",
	"put the blackboard touching the banana",
	"put the blackboard touching the bowl",
	"put the blackboard touching the bowl",
	"put the blackboard touching the bowl",
	"put the blackboard touching the knife",
	"put the blackboard touching the knife",
	"put the blackboard touching the knife",
	"put the blackboard touching the pencil",
	"put the blackboard touching the pencil",
	"put the blackboard touching the pencil",
	"put the blackboard touching the paper sheet",
	"put the blackboard touching the paper sheet",
	"put the blackboard touching the paper sheet",
	"put the bottle touching the block",
	"put the bottle touching the block",
	"put the bottle touching the block",
	"put the bottle touching the ball",
	"put the bottle touching the ball",
	"put the bottle touching the ball",
	"put the bottle touching the plate",
	"put the bottle touching the plate",
	"put the bottle touching the plate",
	"put the bottle touching the cup",
	"put the bottle touching the cup",
	"put the bottle touching the cup",
	"put the bottle touching the disc",
	"put the bottle touching the disc",
	"put the bottle touching the disc",
	"put the bottle touching the book",
	"put the bottle touching the book",
	"put the bottle touching the book",
	"put the bottle touching the blackboard",
	"put the bottle touching the blackboard",
	"put the bottle touching the blackboard",
	"put the bottle touching the grape",
	"put the bottle touching the grape",
	"put the bottle touching the grape",
	"put the bottle touching the apple",
	"put the bottle touching the apple",
	"put the bottle touching the apple",
	"put the bottle touching the banana",
	"put the bottle touching the banana",
	"put the bottle touching the banana",
	"put the bottle touching the bowl",
	"put the bottle touching the bowl",
	"put the bottle touching the bowl",
	"put the bottle touching the knife",
	"put the bottle touching the knife",
	"put the bottle touching the knife",
	"put the bottle touching the pencil",
	"put the bottle touching the pencil",
	"put the bottle touching the pencil",
	"put the bottle touching the paper sheet",
	"put the bottle touching the paper sheet",
	"put the bottle touching the paper sheet",
	"put the grape touching the block",
	"put the grape touching the block",
	"put the grape touching the block",
	"put the grape touching the ball",
	"put the grape touching the ball",
	"put the grape touching the ball",
	"put the grape touching the plate",
	"put the grape touching the plate",
	"put the grape touching the plate",
	"put the grape touching the cup",
	"put the grape touching the cup",
	"put the grape touching the cup",
	"put the grape touching the disc",
	"put the grape touching the disc",
	"put the grape touching the disc",
	"put the grape touching the book",
	"put the grape touching the book",
	"put the grape touching the book",
	"put the grape touching the blackboard",
	"put the grape touching the blackboard",
	"put the grape touching the blackboard",
	"put the grape touching the bottle",
	"put the grape touching the bottle",
	"put the grape touching the bottle",
	"put the grape touching the apple",
	"put the grape touching the apple",
	"put the grape touching the apple",
	"put the grape touching the banana",
	"put the grape touching the banana",
	"put the grape touching the banana",
	"put the grape touching the bowl",
	"put the grape touching the bowl",
	"put the grape touching the bowl",
	"put the grape touching the knife",
	"put the grape touching the knife",
	"put the grape touching the knife",
	"put the grape touching the pencil",
	"put the grape touching the pencil",
	"put the grape touching the pencil",
	"put the grape touching the paper sheet",
	"put the grape touching the paper sheet",
	"put the grape touching the paper sheet",
	"put the apple touching the block",
	"put the apple touching the block",
	"put the apple touching the block",
	"put the apple touching the ball",
	"put the apple touching the ball",
	"put the apple touching the ball",
	"put the apple touching the plate",
	"put the apple touching the plate",
	"put the apple touching the plate",
	"put the apple touching the cup",
	"put the apple touching the cup",
	"put the apple touching the cup",
	"put the apple touching the disc",
	"put the apple touching the disc",
	"put the apple touching the disc",
	"put the apple touching the book",
	"put the apple touching the book",
	"put the apple touching the book",
	"put the apple touching the blackboard",
	"put the apple touching the blackboard",
	"put the apple touching the blackboard",
	"put the apple touching the bottle",
	"put the apple touching the bottle",
	"put the apple touching the bottle",
	"put the apple touching the grape",
	"put the apple touching the grape",
	"put the apple touching the grape",
	"put the apple touching the banana",
	"put the apple touching the banana",
	"put the apple touching the banana",
	"put the apple touching the bowl",
	"put the apple touching the bowl",
	"put the apple touching the bowl",
	"put the apple touching the knife",
	"put the apple touching the knife",
	"put the apple touching the knife",
	"put the apple touching the pencil",
	"put the apple touching the pencil",
	"put the apple touching the pencil",
	"put the apple touching the paper sheet",
	"put the apple touching the paper sheet",
	"put the apple touching the paper sheet",
	"put the banana touching the block",
	"put the banana touching the block",
	"put the banana touching the block",
	"put the banana touching the ball",
	"put the banana touching the ball",
	"put the banana touching the ball",
	"put the banana touching the plate",
	"put the banana touching the plate",
	"put the banana touching the plate",
	"put the banana touching the cup",
	"put the banana touching the cup",
	"put the banana touching the cup",
	"put the banana touching the disc",
	"put the banana touching the disc",
	"put the banana touching the disc",
	"put the banana touching the book",
	"put the banana touching the book",
	"put the banana touching the book",
	"put the banana touching the blackboard",
	"put the banana touching the blackboard",
	"put the banana touching the blackboard",
	"put the banana touching the bottle",
	"put the banana touching the bottle",
	"put the banana touching the bottle",
	"put the banana touching the grape",
	"put the banana touching the grape",
	"put the banana touching the grape",
	"put the banana touching the apple",
	"put the banana touching the apple",
	"put the banana touching the apple",
	"put the banana touching the bowl",
	"put the banana touching the bowl",
	"put the banana touching the bowl",
	"put the banana touching the knife",
	"put the banana touching the knife",
	"put the banana touching the knife",
	"put the banana touching the pencil",
	"put the banana touching the pencil",
	"put the banana touching the pencil",
	"put the banana touching the paper sheet",
	"put the banana touching the paper sheet",
	"put the banana touching the paper sheet",
	"put the bowl touching the block",
	"put the bowl touching the block",
	"put the bowl touching the block",
	"put the bowl touching the ball",
	"put the bowl touching the ball",
	"put the bowl touching the ball",
	"put the bowl touching the plate",
	"put the bowl touching the plate",
	"put the bowl touching the plate",
	"put the bowl touching the cup",
	"put the bowl touching the cup",
	"put the bowl touching the cup",
	"put the bowl touching the disc",
	"put the bowl touching the disc",
	"put the bowl touching the disc",
	"put the bowl touching the book",
	"put the bowl touching the book",
	"put the bowl touching the book",
	"put the bowl touching the blackboard",
	"put the bowl touching the blackboard",
	"put the bowl touching the blackboard",
	"put the bowl touching the bottle",
	"put the bowl touching the bottle",
	"put the bowl touching the bottle",
	"put the bowl touching the grape",
	"put the bowl touching the grape",
	"put the bowl touching the grape",
	"put the bowl touching the apple",
	"put the bowl touching the apple",
	"put the bowl touching the apple",
	"put the bowl touching the banana",
	"put the bowl touching the banana",
	"put the bowl touching the banana",
	"put the bowl touching the knife",
	"put the bowl touching the knife",
	"put the bowl touching the knife",
	"put the bowl touching the pencil",
	"put the bowl touching the pencil",
	"put the bowl touching the pencil",
	"put the bowl touching the paper sheet",
	"put the bowl touching the paper sheet",
	"put the bowl touching the paper sheet",
	"put the knife touching the block",
	"put the knife touching the block",
	"put the knife touching the block",
	"put the knife touching the ball",
	"put the knife touching the ball",
	"put the knife touching the ball",
	"put the knife touching the plate",
	"put the knife touching the plate",
	"put the knife touching the plate",
	"put the knife touching the cup",
	"put the knife touching the cup",
	"put the knife touching the cup",
	"put the knife touching the disc",
	"put the knife touching the disc",
	"put the knife touching the disc",
	"put the knife touching the book",
	"put the knife touching the book",
	"put the knife touching the book",
	"put the knife touching the blackboard",
	"put the knife touching the blackboard",
	"put the knife touching the blackboard",
	"put the knife touching the bottle",
	"put the knife touching the bottle",
	"put the knife touching the bottle",
	"put the knife touching the grape",
	"put the knife touching the grape",
	"put the knife touching the grape",
	"put the knife touching the apple",
	"put the knife touching the apple",
	"put the knife touching the apple",
	"put the knife touching the banana",
	"put the knife touching the banana",
	"put the knife touching the banana",
	"put the knife touching the bowl",
	"put the knife touching the bowl",
	"put the knife touching the bowl",
	"put the knife touching the pencil",
	"put the knife touching the pencil",
	"put the knife touching the pencil",
	"put the knife touching the paper sheet",
	"put the knife touching the paper sheet",
	"put the knife touching the paper sheet",
	"put the pencil touching the block",
	"put the pencil touching the block",
	"put the pencil touching the block",
	"put the pencil touching the ball",
	"put the pencil touching the ball",
	"put the pencil touching the ball",
	"put the pencil touching the plate",
	"put the pencil touching the plate",
	"put the pencil touching the plate",
	"put the pencil touching the cup",
	"put the pencil touching the cup",
	"put the pencil touching the cup",
	"put the pencil touching the disc",
	"put the pencil touching the disc",
	"put the pencil touching the disc",
	"put the pencil touching the book",
	"put the pencil touching the book",
	"put the pencil touching the book",
	"put the pencil touching the blackboard",
	"put the pencil touching the blackboard",
	"put the pencil touching the blackboard",
	"put the pencil touching the bottle",
	"put the pencil touching the bottle",
	"put the pencil touching the bottle",
	"put the pencil touching the grape",
	"put the pencil touching the grape",
	"put the pencil touching the grape",
	"put the pencil touching the apple",
	"put the pencil touching the apple",
	"put the pencil touching the apple",
	"put the pencil touching the banana",
	"put the pencil touching the banana",
	"put the pencil touching the banana",
	"put the pencil touching the bowl",
	"put the pencil touching the bowl",
	"put the pencil touching the bowl",
	"put the pencil touching the knife",
	"put the pencil touching the knife",
	"put the pencil touching the knife",
	"put the pencil touching the paper sheet",
	"put the pencil touching the paper sheet",
	"put the pencil touching the paper sheet",
	"put the paper sheet touching the block",
	"put the paper sheet touching the block",
	"put the paper sheet touching the block",
	"put the paper sheet touching the ball",
	"put the paper sheet touching the ball",
	"put the paper sheet touching the ball",
	"put the paper sheet touching the plate",
	"put the paper sheet touching the plate",
	"put the paper sheet touching the plate",
	"put the paper sheet touching the cup",
	"put the paper sheet touching the cup",
	"put the paper sheet touching the cup",
	"put the paper sheet touching the disc",
	"put the paper sheet touching the disc",
	"put the paper sheet touching the disc",
	"put the paper sheet touching the book",
	"put the paper sheet touching the book",
	"put the paper sheet touching the book",
	"put the paper sheet touching the blackboard",
	"put the paper sheet touching the blackboard",
	"put the paper sheet touching the blackboard",
	"put the paper sheet touching the bottle",
	"put the paper sheet touching the bottle",
	"put the paper sheet touching the bottle",
	"put the paper sheet touching the grape",
	"put the paper sheet touching the grape",
	"put the paper sheet touching the grape",
	"put the paper sheet touching the apple",
	"put the paper sheet touching the apple",
	"put the paper sheet touching the apple",
	"put the paper sheet touching the banana",
	"put the paper sheet touching the banana",
	"put the paper sheet touching the banana",
	"put the paper sheet touching the bowl",
	"put the paper sheet touching the bowl",
	"put the paper sheet touching the bowl",
	"put the paper sheet touching the knife",
	"put the paper sheet touching the knife",
	"put the paper sheet touching the knife",
	"put the paper sheet touching the pencil",
	"put the paper sheet touching the pencil",
	"put the paper sheet touching the pencil",
	]
