sentences = [
	"put the block near the ball",
	"put the block near the ball",
	"put the block near the ball",
	"put the block near the plate",
	"put the block near the plate",
	"put the block near the plate",
	"put the block near the cup",
	"put the block near the cup",
	"put the block near the cup",
	"put the block near the disc",
	"put the block near the disc",
	"put the block near the disc",
	"put the block near the book",
	"put the block near the book",
	"put the block near the book",
	"put the block near the blackboard",
	"put the block near the blackboard",
	"put the block near the blackboard",
	"put the block near the bottle",
	"put the block near the bottle",
	"put the block near the bottle",
	"put the block near the grape",
	"put the block near the grape",
	"put the block near the grape",
	"put the block near the apple",
	"put the block near the apple",
	"put the block near the apple",
	"put the block near the banana",
	"put the block near the banana",
	"put the block near the banana",
	"put the block near the bowl",
	"put the block near the bowl",
	"put the block near the bowl",
	"put the block near the knife",
	"put the block near the knife",
	"put the block near the knife",
	"put the block near the pencil",
	"put the block near the pencil",
	"put the block near the pencil",
	"put the block near the paper sheet",
	"put the block near the paper sheet",
	"put the block near the paper sheet",
	"put the ball near the block",
	"put the ball near the block",
	"put the ball near the block",
	"put the ball near the plate",
	"put the ball near the plate",
	"put the ball near the plate",
	"put the ball near the cup",
	"put the ball near the cup",
	"put the ball near the cup",
	"put the ball near the disc",
	"put the ball near the disc",
	"put the ball near the disc",
	"put the ball near the book",
	"put the ball near the book",
	"put the ball near the book",
	"put the ball near the blackboard",
	"put the ball near the blackboard",
	"put the ball near the blackboard",
	"put the ball near the bottle",
	"put the ball near the bottle",
	"put the ball near the bottle",
	"put the ball near the grape",
	"put the ball near the grape",
	"put the ball near the grape",
	"put the ball near the apple",
	"put the ball near the apple",
	"put the ball near the apple",
	"put the ball near the banana",
	"put the ball near the banana",
	"put the ball near the banana",
	"put the ball near the bowl",
	"put the ball near the bowl",
	"put the ball near the bowl",
	"put the ball near the knife",
	"put the ball near the knife",
	"put the ball near the knife",
	"put the ball near the pencil",
	"put the ball near the pencil",
	"put the ball near the pencil",
	"put the ball near the paper sheet",
	"put the ball near the paper sheet",
	"put the ball near the paper sheet",
	"put the plate near the block",
	"put the plate near the block",
	"put the plate near the block",
	"put the plate near the ball",
	"put the plate near the ball",
	"put the plate near the ball",
	"put the plate near the cup",
	"put the plate near the cup",
	"put the plate near the cup",
	"put the plate near the disc",
	"put the plate near the disc",
	"put the plate near the disc",
	"put the plate near the book",
	"put the plate near the book",
	"put the plate near the book",
	"put the plate near the blackboard",
	"put the plate near the blackboard",
	"put the plate near the blackboard",
	"put the plate near the bottle",
	"put the plate near the bottle",
	"put the plate near the bottle",
	"put the plate near the grape",
	"put the plate near the grape",
	"put the plate near the grape",
	"put the plate near the apple",
	"put the plate near the apple",
	"put the plate near the apple",
	"put the plate near the banana",
	"put the plate near the banana",
	"put the plate near the banana",
	"put the plate near the bowl",
	"put the plate near the bowl",
	"put the plate near the bowl",
	"put the plate near the knife",
	"put the plate near the knife",
	"put the plate near the knife",
	"put the plate near the pencil",
	"put the plate near the pencil",
	"put the plate near the pencil",
	"put the plate near the paper sheet",
	"put the plate near the paper sheet",
	"put the plate near the paper sheet",
	"put the cup near the block",
	"put the cup near the block",
	"put the cup near the block",
	"put the cup near the ball",
	"put the cup near the ball",
	"put the cup near the ball",
	"put the cup near the plate",
	"put the cup near the plate",
	"put the cup near the plate",
	"put the cup near the disc",
	"put the cup near the disc",
	"put the cup near the disc",
	"put the cup near the book",
	"put the cup near the book",
	"put the cup near the book",
	"put the cup near the blackboard",
	"put the cup near the blackboard",
	"put the cup near the blackboard",
	"put the cup near the bottle",
	"put the cup near the bottle",
	"put the cup near the bottle",
	"put the cup near the grape",
	"put the cup near the grape",
	"put the cup near the grape",
	"put the cup near the apple",
	"put the cup near the apple",
	"put the cup near the apple",
	"put the cup near the banana",
	"put the cup near the banana",
	"put the cup near the banana",
	"put the cup near the bowl",
	"put the cup near the bowl",
	"put the cup near the bowl",
	"put the cup near the knife",
	"put the cup near the knife",
	"put the cup near the knife",
	"put the cup near the pencil",
	"put the cup near the pencil",
	"put the cup near the pencil",
	"put the cup near the paper sheet",
	"put the cup near the paper sheet",
	"put the cup near the paper sheet",
	"put the disc near the block",
	"put the disc near the block",
	"put the disc near the block",
	"put the disc near the ball",
	"put the disc near the ball",
	"put the disc near the ball",
	"put the disc near the plate",
	"put the disc near the plate",
	"put the disc near the plate",
	"put the disc near the cup",
	"put the disc near the cup",
	"put the disc near the cup",
	"put the disc near the book",
	"put the disc near the book",
	"put the disc near the book",
	"put the disc near the blackboard",
	"put the disc near the blackboard",
	"put the disc near the blackboard",
	"put the disc near the bottle",
	"put the disc near the bottle",
	"put the disc near the bottle",
	"put the disc near the grape",
	"put the disc near the grape",
	"put the disc near the grape",
	"put the disc near the apple",
	"put the disc near the apple",
	"put the disc near the apple",
	"put the disc near the banana",
	"put the disc near the banana",
	"put the disc near the banana",
	"put the disc near the bowl",
	"put the disc near the bowl",
	"put the disc near the bowl",
	"put the disc near the knife",
	"put the disc near the knife",
	"put the disc near the knife",
	"put the disc near the pencil",
	"put the disc near the pencil",
	"put the disc near the pencil",
	"put the disc near the paper sheet",
	"put the disc near the paper sheet",
	"put the disc near the paper sheet",
	"put the book near the block",
	"put the book near the block",
	"put the book near the block",
	"put the book near the ball",
	"put the book near the ball",
	"put the book near the ball",
	"put the book near the plate",
	"put the book near the plate",
	"put the book near the plate",
	"put the book near the cup",
	"put the book near the cup",
	"put the book near the cup",
	"put the book near the disc",
	"put the book near the disc",
	"put the book near the disc",
	"put the book near the blackboard",
	"put the book near the blackboard",
	"put the book near the blackboard",
	"put the book near the bottle",
	"put the book near the bottle",
	"put the book near the bottle",
	"put the book near the grape",
	"put the book near the grape",
	"put the book near the grape",
	"put the book near the apple",
	"put the book near the apple",
	"put the book near the apple",
	"put the book near the banana",
	"put the book near the banana",
	"put the book near the banana",
	"put the book near the bowl",
	"put the book near the bowl",
	"put the book near the bowl",
	"put the book near the knife",
	"put the book near the knife",
	"put the book near the knife",
	"put the book near the pencil",
	"put the book near the pencil",
	"put the book near the pencil",
	"put the book near the paper sheet",
	"put the book near the paper sheet",
	"put the book near the paper sheet",
	"put the blackboard near the block",
	"put the blackboard near the block",
	"put the blackboard near the block",
	"put the blackboard near the ball",
	"put the blackboard near the ball",
	"put the blackboard near the ball",
	"put the blackboard near the plate",
	"put the blackboard near the plate",
	"put the blackboard near the plate",
	"put the blackboard near the cup",
	"put the blackboard near the cup",
	"put the blackboard near the cup",
	"put the blackboard near the disc",
	"put the blackboard near the disc",
	"put the blackboard near the disc",
	"put the blackboard near the book",
	"put the blackboard near the book",
	"put the blackboard near the book",
	"put the blackboard near the bottle",
	"put the blackboard near the bottle",
	"put the blackboard near the bottle",
	"put the blackboard near the grape",
	"put the blackboard near the grape",
	"put the blackboard near the grape",
	"put the blackboard near the apple",
	"put the blackboard near the apple",
	"put the blackboard near the apple",
	"put the blackboard near the banana",
	"put the blackboard near the banana",
	"put the blackboard near the banana",
	"put the blackboard near the bowl",
	"put the blackboard near the bowl",
	"put the blackboard near the bowl",
	"put the blackboard near the knife",
	"put the blackboard near the knife",
	"put the blackboard near the knife",
	"put the blackboard near the pencil",
	"put the blackboard near the pencil",
	"put the blackboard near the pencil",
	"put the blackboard near the paper sheet",
	"put the blackboard near the paper sheet",
	"put the blackboard near the paper sheet",
	"put the bottle near the block",
	"put the bottle near the block",
	"put the bottle near the block",
	"put the bottle near the ball",
	"put the bottle near the ball",
	"put the bottle near the ball",
	"put the bottle near the plate",
	"put the bottle near the plate",
	"put the bottle near the plate",
	"put the bottle near the cup",
	"put the bottle near the cup",
	"put the bottle near the cup",
	"put the bottle near the disc",
	"put the bottle near the disc",
	"put the bottle near the disc",
	"put the bottle near the book",
	"put the bottle near the book",
	"put the bottle near the book",
	"put the bottle near the blackboard",
	"put the bottle near the blackboard",
	"put the bottle near the blackboard",
	"put the bottle near the grape",
	"put the bottle near the grape",
	"put the bottle near the grape",
	"put the bottle near the apple",
	"put the bottle near the apple",
	"put the bottle near the apple",
	"put the bottle near the banana",
	"put the bottle near the banana",
	"put the bottle near the banana",
	"put the bottle near the bowl",
	"put the bottle near the bowl",
	"put the bottle near the bowl",
	"put the bottle near the knife",
	"put the bottle near the knife",
	"put the bottle near the knife",
	"put the bottle near the pencil",
	"put the bottle near the pencil",
	"put the bottle near the pencil",
	"put the bottle near the paper sheet",
	"put the bottle near the paper sheet",
	"put the bottle near the paper sheet",
	"put the grape near the block",
	"put the grape near the block",
	"put the grape near the block",
	"put the grape near the ball",
	"put the grape near the ball",
	"put the grape near the ball",
	"put the grape near the plate",
	"put the grape near the plate",
	"put the grape near the plate",
	"put the grape near the cup",
	"put the grape near the cup",
	"put the grape near the cup",
	"put the grape near the disc",
	"put the grape near the disc",
	"put the grape near the disc",
	"put the grape near the book",
	"put the grape near the book",
	"put the grape near the book",
	"put the grape near the blackboard",
	"put the grape near the blackboard",
	"put the grape near the blackboard",
	"put the grape near the bottle",
	"put the grape near the bottle",
	"put the grape near the bottle",
	"put the grape near the apple",
	"put the grape near the apple",
	"put the grape near the apple",
	"put the grape near the banana",
	"put the grape near the banana",
	"put the grape near the banana",
	"put the grape near the bowl",
	"put the grape near the bowl",
	"put the grape near the bowl",
	"put the grape near the knife",
	"put the grape near the knife",
	"put the grape near the knife",
	"put the grape near the pencil",
	"put the grape near the pencil",
	"put the grape near the pencil",
	"put the grape near the paper sheet",
	"put the grape near the paper sheet",
	"put the grape near the paper sheet",
	"put the apple near the block",
	"put the apple near the block",
	"put the apple near the block",
	"put the apple near the ball",
	"put the apple near the ball",
	"put the apple near the ball",
	"put the apple near the plate",
	"put the apple near the plate",
	"put the apple near the plate",
	"put the apple near the cup",
	"put the apple near the cup",
	"put the apple near the cup",
	"put the apple near the disc",
	"put the apple near the disc",
	"put the apple near the disc",
	"put the apple near the book",
	"put the apple near the book",
	"put the apple near the book",
	"put the apple near the blackboard",
	"put the apple near the blackboard",
	"put the apple near the blackboard",
	"put the apple near the bottle",
	"put the apple near the bottle",
	"put the apple near the bottle",
	"put the apple near the grape",
	"put the apple near the grape",
	"put the apple near the grape",
	"put the apple near the banana",
	"put the apple near the banana",
	"put the apple near the banana",
	"put the apple near the bowl",
	"put the apple near the bowl",
	"put the apple near the bowl",
	"put the apple near the knife",
	"put the apple near the knife",
	"put the apple near the knife",
	"put the apple near the pencil",
	"put the apple near the pencil",
	"put the apple near the pencil",
	"put the apple near the paper sheet",
	"put the apple near the paper sheet",
	"put the apple near the paper sheet",
	"put the banana near the block",
	"put the banana near the block",
	"put the banana near the block",
	"put the banana near the ball",
	"put the banana near the ball",
	"put the banana near the ball",
	"put the banana near the plate",
	"put the banana near the plate",
	"put the banana near the plate",
	"put the banana near the cup",
	"put the banana near the cup",
	"put the banana near the cup",
	"put the banana near the disc",
	"put the banana near the disc",
	"put the banana near the disc",
	"put the banana near the book",
	"put the banana near the book",
	"put the banana near the book",
	"put the banana near the blackboard",
	"put the banana near the blackboard",
	"put the banana near the blackboard",
	"put the banana near the bottle",
	"put the banana near the bottle",
	"put the banana near the bottle",
	"put the banana near the grape",
	"put the banana near the grape",
	"put the banana near the grape",
	"put the banana near the apple",
	"put the banana near the apple",
	"put the banana near the apple",
	"put the banana near the bowl",
	"put the banana near the bowl",
	"put the banana near the bowl",
	"put the banana near the knife",
	"put the banana near the knife",
	"put the banana near the knife",
	"put the banana near the pencil",
	"put the banana near the pencil",
	"put the banana near the pencil",
	"put the banana near the paper sheet",
	"put the banana near the paper sheet",
	"put the banana near the paper sheet",
	"put the bowl near the block",
	"put the bowl near the block",
	"put the bowl near the block",
	"put the bowl near the ball",
	"put the bowl near the ball",
	"put the bowl near the ball",
	"put the bowl near the plate",
	"put the bowl near the plate",
	"put the bowl near the plate",
	"put the bowl near the cup",
	"put the bowl near the cup",
	"put the bowl near the cup",
	"put the bowl near the disc",
	"put the bowl near the disc",
	"put the bowl near the disc",
	"put the bowl near the book",
	"put the bowl near the book",
	"put the bowl near the book",
	"put the bowl near the blackboard",
	"put the bowl near the blackboard",
	"put the bowl near the blackboard",
	"put the bowl near the bottle",
	"put the bowl near the bottle",
	"put the bowl near the bottle",
	"put the bowl near the grape",
	"put the bowl near the grape",
	"put the bowl near the grape",
	"put the bowl near the apple",
	"put the bowl near the apple",
	"put the bowl near the apple",
	"put the bowl near the banana",
	"put the bowl near the banana",
	"put the bowl near the banana",
	"put the bowl near the knife",
	"put the bowl near the knife",
	"put the bowl near the knife",
	"put the bowl near the pencil",
	"put the bowl near the pencil",
	"put the bowl near the pencil",
	"put the bowl near the paper sheet",
	"put the bowl near the paper sheet",
	"put the bowl near the paper sheet",
	"put the knife near the block",
	"put the knife near the block",
	"put the knife near the block",
	"put the knife near the ball",
	"put the knife near the ball",
	"put the knife near the ball",
	"put the knife near the plate",
	"put the knife near the plate",
	"put the knife near the plate",
	"put the knife near the cup",
	"put the knife near the cup",
	"put the knife near the cup",
	"put the knife near the disc",
	"put the knife near the disc",
	"put the knife near the disc",
	"put the knife near the book",
	"put the knife near the book",
	"put the knife near the book",
	"put the knife near the blackboard",
	"put the knife near the blackboard",
	"put the knife near the blackboard",
	"put the knife near the bottle",
	"put the knife near the bottle",
	"put the knife near the bottle",
	"put the knife near the grape",
	"put the knife near the grape",
	"put the knife near the grape",
	"put the knife near the apple",
	"put the knife near the apple",
	"put the knife near the apple",
	"put the knife near the banana",
	"put the knife near the banana",
	"put the knife near the banana",
	"put the knife near the bowl",
	"put the knife near the bowl",
	"put the knife near the bowl",
	"put the knife near the pencil",
	"put the knife near the pencil",
	"put the knife near the pencil",
	"put the knife near the paper sheet",
	"put the knife near the paper sheet",
	"put the knife near the paper sheet",
	"put the pencil near the block",
	"put the pencil near the block",
	"put the pencil near the block",
	"put the pencil near the ball",
	"put the pencil near the ball",
	"put the pencil near the ball",
	"put the pencil near the plate",
	"put the pencil near the plate",
	"put the pencil near the plate",
	"put the pencil near the cup",
	"put the pencil near the cup",
	"put the pencil near the cup",
	"put the pencil near the disc",
	"put the pencil near the disc",
	"put the pencil near the disc",
	"put the pencil near the book",
	"put the pencil near the book",
	"put the pencil near the book",
	"put the pencil near the blackboard",
	"put the pencil near the blackboard",
	"put the pencil near the blackboard",
	"put the pencil near the bottle",
	"put the pencil near the bottle",
	"put the pencil near the bottle",
	"put the pencil near the grape",
	"put the pencil near the grape",
	"put the pencil near the grape",
	"put the pencil near the apple",
	"put the pencil near the apple",
	"put the pencil near the apple",
	"put the pencil near the banana",
	"put the pencil near the banana",
	"put the pencil near the banana",
	"put the pencil near the bowl",
	"put the pencil near the bowl",
	"put the pencil near the bowl",
	"put the pencil near the knife",
	"put the pencil near the knife",
	"put the pencil near the knife",
	"put the pencil near the paper sheet",
	"put the pencil near the paper sheet",
	"put the pencil near the paper sheet",
	"put the paper sheet near the block",
	"put the paper sheet near the block",
	"put the paper sheet near the block",
	"put the paper sheet near the ball",
	"put the paper sheet near the ball",
	"put the paper sheet near the ball",
	"put the paper sheet near the plate",
	"put the paper sheet near the plate",
	"put the paper sheet near the plate",
	"put the paper sheet near the cup",
	"put the paper sheet near the cup",
	"put the paper sheet near the cup",
	"put the paper sheet near the disc",
	"put the paper sheet near the disc",
	"put the paper sheet near the disc",
	"put the paper sheet near the book",
	"put the paper sheet near the book",
	"put the paper sheet near the book",
	"put the paper sheet near the blackboard",
	"put the paper sheet near the blackboard",
	"put the paper sheet near the blackboard",
	"put the paper sheet near the bottle",
	"put the paper sheet near the bottle",
	"put the paper sheet near the bottle",
	"put the paper sheet near the grape",
	"put the paper sheet near the grape",
	"put the paper sheet near the grape",
	"put the paper sheet near the apple",
	"put the paper sheet near the apple",
	"put the paper sheet near the apple",
	"put the paper sheet near the banana",
	"put the paper sheet near the banana",
	"put the paper sheet near the banana",
	"put the paper sheet near the bowl",
	"put the paper sheet near the bowl",
	"put the paper sheet near the bowl",
	"put the paper sheet near the knife",
	"put the paper sheet near the knife",
	"put the paper sheet near the knife",
	"put the paper sheet near the pencil",
	"put the paper sheet near the pencil",
	"put the paper sheet near the pencil",
	]
