sentences = [
	"spin the block",
	"spin the block",
	"spin the block",
	"spin the ball",
	"spin the ball",
	"spin the ball",
	"spin the plate",
	"spin the plate",
	"spin the plate",
	"spin the cup",
	"spin the cup",
	"spin the cup",
	"spin the disc",
	"spin the disc",
	"spin the disc",
	"spin the book",
	"spin the book",
	"spin the book",
	"spin the blackboard",
	"spin the blackboard",
	"spin the blackboard",
	"spin the bottle",
	"spin the bottle",
	"spin the bottle",
	"spin the grape",
	"spin the grape",
	"spin the grape",
	"spin the apple",
	"spin the apple",
	"spin the apple",
	"spin the banana",
	"spin the banana",
	"spin the banana",
	"spin the bowl",
	"spin the bowl",
	"spin the bowl",
	"spin the knife",
	"spin the knife",
	"spin the knife",
	"spin the pencil",
	"spin the pencil",
	"spin the pencil",
	"spin the paper sheet",
	"spin the paper sheet",
	"spin the paper sheet"
	]
