sentences = [
	"stack the block and the grape",
	"stack the block and the grape",
	"stack the block and the grape",
	"stack the block and the ball",
	"stack the block and the ball",
	"stack the block and the ball",
	"stack the block and the apple",
	"stack the block and the apple",
	"stack the block and the apple",
	"stack the block and the plate",
	"stack the block and the plate",
	"stack the block and the plate",
	"stack the block and the banana",
	"stack the block and the banana",
	"stack the block and the banana",
	"stack the block and the cup",
	"stack the block and the cup",
	"stack the block and the cup",
	"stack the block and the disc",
	"stack the block and the disc",
	"stack the block and the disc",
	"stack the block and the bowl",
	"stack the block and the bowl",
	"stack the block and the bowl",
	"stack the block and the knife",
	"stack the block and the knife",
	"stack the block and the knife",
	"stack the block and the book",
	"stack the block and the book",
	"stack the block and the book",
	"stack the block and the pencil",
	"stack the block and the pencil",
	"stack the block and the pencil",
	"stack the block and the paper sheet",
	"stack the block and the paper sheet",
	"stack the block and the paper sheet",
	"stack the block and the bottle",
	"stack the block and the bottle",
	"stack the block and the bottle",
	"stack the grape and the block",
	"stack the grape and the block",
	"stack the grape and the block",
	"stack the grape and the ball",
	"stack the grape and the ball",
	"stack the grape and the ball",
	"stack the grape and the apple",
	"stack the grape and the apple",
	"stack the grape and the apple",
	"stack the grape and the plate",
	"stack the grape and the plate",
	"stack the grape and the plate",
	"stack the grape and the banana",
	"stack the grape and the banana",
	"stack the grape and the banana",
	"stack the grape and the cup",
	"stack the grape and the cup",
	"stack the grape and the cup",
	"stack the grape and the disc",
	"stack the grape and the disc",
	"stack the grape and the disc",
	"stack the grape and the bowl",
	"stack the grape and the bowl",
	"stack the grape and the bowl",
	"stack the grape and the knife",
	"stack the grape and the knife",
	"stack the grape and the knife",
	"stack the grape and the book",
	"stack the grape and the book",
	"stack the grape and the book",
	"stack the grape and the pencil",
	"stack the grape and the pencil",
	"stack the grape and the pencil",
	"stack the grape and the blackboard",
	"stack the grape and the blackboard",
	"stack the grape and the blackboard",
	"stack the grape and the paper sheet",
	"stack the grape and the paper sheet",
	"stack the grape and the paper sheet",
	"stack the grape and the bottle",
	"stack the grape and the bottle",
	"stack the grape and the bottle",
	"stack the ball and the block",
	"stack the ball and the block",
	"stack the ball and the block",
	"stack the ball and the grape",
	"stack the ball and the grape",
	"stack the ball and the grape",
	"stack the ball and the apple",
	"stack the ball and the apple",
	"stack the ball and the apple",
	"stack the ball and the plate",
	"stack the ball and the plate",
	"stack the ball and the plate",
	"stack the ball and the banana",
	"stack the ball and the banana",
	"stack the ball and the banana",
	"stack the ball and the cup",
	"stack the ball and the cup",
	"stack the ball and the cup",
	"stack the ball and the disc",
	"stack the ball and the disc",
	"stack the ball and the disc",
	"stack the ball and the bowl",
	"stack the ball and the bowl",
	"stack the ball and the bowl",
	"stack the ball and the knife",
	"stack the ball and the knife",
	"stack the ball and the knife",
	"stack the ball and the book",
	"stack the ball and the book",
	"stack the ball and the book",
	"stack the ball and the pencil",
	"stack the ball and the pencil",
	"stack the ball and the pencil",
	"stack the ball and the blackboard",
	"stack the ball and the blackboard",
	"stack the ball and the blackboard",
	"stack the ball and the paper sheet",
	"stack the ball and the paper sheet",
	"stack the ball and the paper sheet",
	"stack the ball and the bottle",
	"stack the ball and the bottle",
	"stack the ball and the bottle",
	"stack the apple and the block",
	"stack the apple and the block",
	"stack the apple and the block",
	"stack the apple and the grape",
	"stack the apple and the grape",
	"stack the apple and the grape",
	"stack the apple and the ball",
	"stack the apple and the ball",
	"stack the apple and the ball",
	"stack the apple and the plate",
	"stack the apple and the plate",
	"stack the apple and the plate",
	"stack the apple and the banana",
	"stack the apple and the banana",
	"stack the apple and the banana",
	"stack the apple and the cup",
	"stack the apple and the cup",
	"stack the apple and the cup",
	"stack the apple and the disc",
	"stack the apple and the disc",
	"stack the apple and the disc",
	"stack the apple and the bowl",
	"stack the apple and the bowl",
	"stack the apple and the bowl",
	"stack the apple and the knife",
	"stack the apple and the knife",
	"stack the apple and the knife",
	"stack the apple and the book",
	"stack the apple and the book",
	"stack the apple and the book",
	"stack the apple and the pencil",
	"stack the apple and the pencil",
	"stack the apple and the pencil",
	"stack the apple and the paper sheet",
	"stack the apple and the paper sheet",
	"stack the apple and the paper sheet",
	"stack the apple and the bottle",
	"stack the apple and the bottle",
	"stack the apple and the bottle",
	"stack the plate and the block",
	"stack the plate and the block",
	"stack the plate and the block",
	"stack the plate and the grape",
	"stack the plate and the grape",
	"stack the plate and the grape",
	"stack the plate and the ball",
	"stack the plate and the ball",
	"stack the plate and the ball",
	"stack the plate and the apple",
	"stack the plate and the apple",
	"stack the plate and the apple",
	"stack the plate and the banana",
	"stack the plate and the banana",
	"stack the plate and the banana",
	"stack the plate and the cup",
	"stack the plate and the cup",
	"stack the plate and the cup",
	"stack the plate and the disc",
	"stack the plate and the disc",
	"stack the plate and the disc",
	"stack the plate and the bowl",
	"stack the plate and the bowl",
	"stack the plate and the bowl",
	"stack the plate and the knife",
	"stack the plate and the knife",
	"stack the plate and the knife",
	"stack the plate and the book",
	"stack the plate and the book",
	"stack the plate and the book",
	"stack the plate and the pencil",
	"stack the plate and the pencil",
	"stack the plate and the pencil",
	"stack the plate and the paper sheet",
	"stack the plate and the paper sheet",
	"stack the plate and the paper sheet",
	"stack the plate and the bottle",
	"stack the plate and the bottle",
	"stack the plate and the bottle",
	"stack the banana and the block",
	"stack the banana and the block",
	"stack the banana and the block",
	"stack the banana and the grape",
	"stack the banana and the grape",
	"stack the banana and the grape",
	"stack the banana and the ball",
	"stack the banana and the ball",
	"stack the banana and the ball",
	"stack the banana and the apple",
	"stack the banana and the apple",
	"stack the banana and the apple",
	"stack the banana and the plate",
	"stack the banana and the plate",
	"stack the banana and the plate",
	"stack the banana and the cup",
	"stack the banana and the cup",
	"stack the banana and the cup",
	"stack the banana and the disc",
	"stack the banana and the disc",
	"stack the banana and the disc",
	"stack the banana and the bowl",
	"stack the banana and the bowl",
	"stack the banana and the bowl",
	"stack the banana and the knife",
	"stack the banana and the knife",
	"stack the banana and the knife",
	"stack the banana and the book",
	"stack the banana and the book",
	"stack the banana and the book",
	"stack the banana and the pencil",
	"stack the banana and the pencil",
	"stack the banana and the pencil",
	"stack the banana and the paper sheet",
	"stack the banana and the paper sheet",
	"stack the banana and the paper sheet",
	"stack the banana and the bottle",
	"stack the banana and the bottle",
	"stack the banana and the bottle",
	"stack the cup and the block",
	"stack the cup and the block",
	"stack the cup and the block",
	"stack the cup and the grape",
	"stack the cup and the grape",
	"stack the cup and the grape",
	"stack the cup and the ball",
	"stack the cup and the ball",
	"stack the cup and the ball",
	"stack the cup and the apple",
	"stack the cup and the apple",
	"stack the cup and the apple",
	"stack the cup and the plate",
	"stack the cup and the plate",
	"stack the cup and the plate",
	"stack the cup and the banana",
	"stack the cup and the banana",
	"stack the cup and the banana",
	"stack the cup and the disc",
	"stack the cup and the disc",
	"stack the cup and the disc",
	"stack the cup and the bowl",
	"stack the cup and the bowl",
	"stack the cup and the bowl",
	"stack the cup and the knife",
	"stack the cup and the knife",
	"stack the cup and the knife",
	"stack the cup and the book",
	"stack the cup and the book",
	"stack the cup and the book",
	"stack the cup and the pencil",
	"stack the cup and the pencil",
	"stack the cup and the pencil",
	"stack the cup and the paper sheet",
	"stack the cup and the paper sheet",
	"stack the cup and the paper sheet",
	"stack the cup and the bottle",
	"stack the cup and the bottle",
	"stack the cup and the bottle",
	"stack the disc and the block",
	"stack the disc and the block",
	"stack the disc and the block",
	"stack the disc and the grape",
	"stack the disc and the grape",
	"stack the disc and the grape",
	"stack the disc and the ball",
	"stack the disc and the ball",
	"stack the disc and the ball",
	"stack the disc and the apple",
	"stack the disc and the apple",
	"stack the disc and the apple",
	"stack the disc and the plate",
	"stack the disc and the plate",
	"stack the disc and the plate",
	"stack the disc and the banana",
	"stack the disc and the banana",
	"stack the disc and the banana",
	"stack the disc and the cup",
	"stack the disc and the cup",
	"stack the disc and the cup",
	"stack the disc and the bowl",
	"stack the disc and the bowl",
	"stack the disc and the bowl",
	"stack the disc and the knife",
	"stack the disc and the knife",
	"stack the disc and the knife",
	"stack the disc and the book",
	"stack the disc and the book",
	"stack the disc and the book",
	"stack the disc and the pencil",
	"stack the disc and the pencil",
	"stack the disc and the pencil",
	"stack the disc and the paper sheet",
	"stack the disc and the paper sheet",
	"stack the disc and the paper sheet",
	"stack the disc and the bottle",
	"stack the disc and the bottle",
	"stack the disc and the bottle",
	"stack the bowl and the block",
	"stack the bowl and the block",
	"stack the bowl and the block",
	"stack the bowl and the grape",
	"stack the bowl and the grape",
	"stack the bowl and the grape",
	"stack the bowl and the ball",
	"stack the bowl and the ball",
	"stack the bowl and the ball",
	"stack the bowl and the apple",
	"stack the bowl and the apple",
	"stack the bowl and the apple",
	"stack the bowl and the plate",
	"stack the bowl and the plate",
	"stack the bowl and the plate",
	"stack the bowl and the banana",
	"stack the bowl and the banana",
	"stack the bowl and the banana",
	"stack the bowl and the cup",
	"stack the bowl and the cup",
	"stack the bowl and the cup",
	"stack the bowl and the disc",
	"stack the bowl and the disc",
	"stack the bowl and the disc",
	"stack the bowl and the knife",
	"stack the bowl and the knife",
	"stack the bowl and the knife",
	"stack the bowl and the book",
	"stack the bowl and the book",
	"stack the bowl and the book",
	"stack the bowl and the pencil",
	"stack the bowl and the pencil",
	"stack the bowl and the pencil",
	"stack the bowl and the paper sheet",
	"stack the bowl and the paper sheet",
	"stack the bowl and the paper sheet",
	"stack the bowl and the bottle",
	"stack the bowl and the bottle",
	"stack the bowl and the bottle",
	"stack the knife and the block",
	"stack the knife and the block",
	"stack the knife and the block",
	"stack the knife and the grape",
	"stack the knife and the grape",
	"stack the knife and the grape",
	"stack the knife and the ball",
	"stack the knife and the ball",
	"stack the knife and the ball",
	"stack the knife and the apple",
	"stack the knife and the apple",
	"stack the knife and the apple",
	"stack the knife and the plate",
	"stack the knife and the plate",
	"stack the knife and the plate",
	"stack the knife and the banana",
	"stack the knife and the banana",
	"stack the knife and the banana",
	"stack the knife and the cup",
	"stack the knife and the cup",
	"stack the knife and the cup",
	"stack the knife and the disc",
	"stack the knife and the disc",
	"stack the knife and the disc",
	"stack the knife and the bowl",
	"stack the knife and the bowl",
	"stack the knife and the bowl",
	"stack the knife and the book",
	"stack the knife and the book",
	"stack the knife and the book",
	"stack the knife and the pencil",
	"stack the knife and the pencil",
	"stack the knife and the pencil",
	"stack the knife and the paper sheet",
	"stack the knife and the paper sheet",
	"stack the knife and the paper sheet",
	"stack the knife and the bottle",
	"stack the knife and the bottle",
	"stack the knife and the bottle",
	"stack the book and the block",
	"stack the book and the block",
	"stack the book and the block",
	"stack the book and the grape",
	"stack the book and the grape",
	"stack the book and the grape",
	"stack the book and the ball",
	"stack the book and the ball",
	"stack the book and the ball",
	"stack the book and the apple",
	"stack the book and the apple",
	"stack the book and the apple",
	"stack the book and the plate",
	"stack the book and the plate",
	"stack the book and the plate",
	"stack the book and the banana",
	"stack the book and the banana",
	"stack the book and the banana",
	"stack the book and the cup",
	"stack the book and the cup",
	"stack the book and the cup",
	"stack the book and the disc",
	"stack the book and the disc",
	"stack the book and the disc",
	"stack the book and the bowl",
	"stack the book and the bowl",
	"stack the book and the bowl",
	"stack the book and the knife",
	"stack the book and the knife",
	"stack the book and the knife",
	"stack the book and the pencil",
	"stack the book and the pencil",
	"stack the book and the pencil",
	"stack the book and the paper sheet",
	"stack the book and the paper sheet",
	"stack the book and the paper sheet",
	"stack the book and the bottle",
	"stack the book and the bottle",
	"stack the book and the bottle",
	"stack the pencil and the block",
	"stack the pencil and the block",
	"stack the pencil and the block",
	"stack the pencil and the grape",
	"stack the pencil and the grape",
	"stack the pencil and the grape",
	"stack the pencil and the ball",
	"stack the pencil and the ball",
	"stack the pencil and the ball",
	"stack the pencil and the apple",
	"stack the pencil and the apple",
	"stack the pencil and the apple",
	"stack the pencil and the plate",
	"stack the pencil and the plate",
	"stack the pencil and the plate",
	"stack the pencil and the banana",
	"stack the pencil and the banana",
	"stack the pencil and the banana",
	"stack the pencil and the cup",
	"stack the pencil and the cup",
	"stack the pencil and the cup",
	"stack the pencil and the disc",
	"stack the pencil and the disc",
	"stack the pencil and the disc",
	"stack the pencil and the bowl",
	"stack the pencil and the bowl",
	"stack the pencil and the bowl",
	"stack the pencil and the knife",
	"stack the pencil and the knife",
	"stack the pencil and the knife",
	"stack the pencil and the book",
	"stack the pencil and the book",
	"stack the pencil and the book",
	"stack the pencil and the paper sheet",
	"stack the pencil and the paper sheet",
	"stack the pencil and the paper sheet",
	"stack the pencil and the bottle",
	"stack the pencil and the bottle",
	"stack the pencil and the bottle",
	"stack the blackboard and the block",
	"stack the blackboard and the block",
	"stack the blackboard and the block",
	"stack the paper sheet and the block",
	"stack the paper sheet and the block",
	"stack the paper sheet and the block",
	"stack the paper sheet and the grape",
	"stack the paper sheet and the grape",
	"stack the paper sheet and the grape",
	"stack the paper sheet and the ball",
	"stack the paper sheet and the ball",
	"stack the paper sheet and the ball",
	"stack the paper sheet and the apple",
	"stack the paper sheet and the apple",
	"stack the paper sheet and the apple",
	"stack the paper sheet and the plate",
	"stack the paper sheet and the plate",
	"stack the paper sheet and the plate",
	"stack the paper sheet and the banana",
	"stack the paper sheet and the banana",
	"stack the paper sheet and the banana",
	"stack the paper sheet and the cup",
	"stack the paper sheet and the cup",
	"stack the paper sheet and the cup",
	"stack the paper sheet and the disc",
	"stack the paper sheet and the disc",
	"stack the paper sheet and the disc",
	"stack the paper sheet and the bowl",
	"stack the paper sheet and the bowl",
	"stack the paper sheet and the bowl",
	"stack the paper sheet and the knife",
	"stack the paper sheet and the knife",
	"stack the paper sheet and the knife",
	"stack the paper sheet and the book",
	"stack the paper sheet and the book",
	"stack the paper sheet and the book",
	"stack the paper sheet and the pencil",
	"stack the paper sheet and the pencil",
	"stack the paper sheet and the pencil",
	"stack the paper sheet and the bottle",
	"stack the paper sheet and the bottle",
	"stack the paper sheet and the bottle",
	"stack the bottle and the block",
	"stack the bottle and the block",
	"stack the bottle and the block",
	"stack the bottle and the grape",
	"stack the bottle and the grape",
	"stack the bottle and the grape",
	"stack the bottle and the ball",
	"stack the bottle and the ball",
	"stack the bottle and the ball",
	"stack the bottle and the apple",
	"stack the bottle and the apple",
	"stack the bottle and the apple",
	"stack the bottle and the plate",
	"stack the bottle and the plate",
	"stack the bottle and the plate",
	"stack the bottle and the banana",
	"stack the bottle and the banana",
	"stack the bottle and the banana",
	"stack the bottle and the cup",
	"stack the bottle and the cup",
	"stack the bottle and the cup",
	"stack the bottle and the disc",
	"stack the bottle and the disc",
	"stack the bottle and the disc",
	"stack the bottle and the bowl",
	"stack the bottle and the bowl",
	"stack the bottle and the bowl",
	"stack the bottle and the knife",
	"stack the bottle and the knife",
	"stack the bottle and the knife",
	"stack the bottle and the book",
	"stack the bottle and the book",
	"stack the bottle and the book",
	"stack the bottle and the pencil",
	"stack the bottle and the pencil",
	"stack the bottle and the pencil",
	"stack the bottle and the paper sheet",
	"stack the bottle and the paper sheet",
	"stack the bottle and the paper sheet"
	]
