sentences = [
	"touch the block",
	"touch the block",
	"touch the block",
	"touch the ball",
	"touch the ball",
	"touch the ball",
	"touch the plate",
	"touch the plate",
	"touch the plate",
	"touch the cup",
	"touch the cup",
	"touch the cup",
	"touch the disc",
	"touch the disc",
	"touch the disc",
	"touch the book",
	"touch the book",
	"touch the book",
	"touch the blackboard",
	"touch the blackboard",
	"touch the blackboard",
	"touch the bottle",
	"touch the bottle",
	"touch the bottle",
	"touch the grape",
	"touch the grape",
	"touch the grape",
	"touch the apple",
	"touch the apple",
	"touch the apple",
	"touch the banana",
	"touch the banana",
	"touch the banana",
	"touch the bowl",
	"touch the bowl",
	"touch the bowl",
	"touch the knife",
	"touch the knife",
	"touch the knife",
	"touch the pencil",
	"touch the pencil",
	"touch the pencil",
	"touch the paper sheet",
	"touch the paper sheet",
	"touch the paper sheet"
	]
